// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID                 int32              `json:"id"`
	Site               pgtype.Text        `json:"site"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	ParentDepartmentID pgtype.Int2        `json:"parent_department_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedBy          pgtype.Text        `json:"updated_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int32            `json:"id"`
	Site        pgtype.Text      `json:"site"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	IsActive    pgtype.Bool      `json:"is_active"`
}

type User struct {
	ID           int32              `json:"id"`
	Site         pgtype.Text        `json:"site"`
	EmployeeID   string             `json:"employee_id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	DepartmentID pgtype.Int2        `json:"department_id"`
	Role         pgtype.Int2        `json:"role"`
	Status       pgtype.Int2        `json:"status"`
	StatusReason pgtype.Text        `json:"status_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedBy    pgtype.Text        `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}

type UserStatus struct {
	ID          int32            `json:"id"`
	Site        pgtype.Text      `json:"site"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedBy   pgtype.Text      `json:"updated_by"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
