// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	// sqlc/queries/user.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	GetUserByEmployeeID(ctx context.Context, employeeID string) (GetUserByEmployeeIDRow, error)
	GetUserByUserName(ctx context.Context, username string) (GetUserByUserNameRow, error)
}

var _ Querier = (*Queries)(nil)
